# Generated by Django 6.0.1 on 2026-01-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название блога",
                        max_length=20,
                        verbose_name="Название блога",
                    ),
                ),
                (
                    "content_blog",
                    models.TextField(
                        blank=True,
                        help_text="введите содержимое",
                        null=True,
                        verbose_name="Содержимое",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение для блога",
                        null=True,
                        upload_to="photo",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "date_publication",
                    models.DateField(
                        blank=True,
                        help_text="Дата публикации",
                        null=True,
                        verbose_name="Дата публикации",
                    ),
                ),
                ("bool_blog", models.BooleanField(default=False)),
                (
                    "view_cointer",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество просмотров",
                        verbose_name="Счетчик просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
