# Generated by Django 6.0.1 on 2026-01-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="bool_blog",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
